apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::191469844238:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15CA8K5JGXWFY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::191469844238:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-04T20:56:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1319"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 982d3a70-2cc9-46aa-b052-89b6bd589fde
